source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in analytic.gemspec.
gemspec
group :development, :test do
    gem 'rspec-rails'
    gem 'factory_bot_rails'
end
# To use a debugger
# gem 'byebug', group: [:development, :test]
