---
:concurrency: 5
staging:
  :concurrency: 4
production:
  :concurrency: 5
:queues:
  - critical
  - mailers
  - default
  - low
  - importing_job
  - downloading_job
  - ecdis_mail_checker
  - sync_vessel
  - cleaning_job
