#Run per hour
- class_name: Analytic::SimJob::ImportingJob
  start_at: "00:30"
  interval:
  params:

- class_name: Analytic::SpasJob::ImportingJob
  start_at: "00:00"
  interval:
  params:

# This job is working only in staging enviroment
# - class_name: Analytic::SimSpasCleanJob
#   start_at: "00:00"
#   interval:
#   params:
